
services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - .config/variables/.env.development.local
    environment:
      NODE_ENV: development
      DB_PASSWORD: /run/secrets/db-password
    secrets:
      - db-password
    #depends_on:
    #  db:
    #    condition: service_healthy
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
secrets:
  db-password:
    file: .config/secrets/db-password-secret.txt